### ISSUE TITLE
datetime & GeoJSON BBOX vs Extents?

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/ogcapi-records#120]
I realized I've been confused by having Extents (spatial and temporal) as direct fields in the GeoJSON properties.

I think it's a lot more useful to actually 'map' those into GeoJSON. In STAC we just use the GeoJSON BBOX to represent the spatial extent. And then we have either `datetime` or `start_datetime` and `end_datetime` (see https://github.com/radiantearth/stac-spec/blob/v1.0.0/item-spec/common-metadata.md#date-and-time-range) for the time. 

I don't think it's so important that these align exactly. But imho there's a big benefit of having 'flat' properties - they'll show up in any GeoJSON reader. The 'extent' object in most GeoJSON displays is just going to be this weird geojson chunk. But if it's the start and end datetime those will be values the user always sees, and the BBOX can also be easily read in and displayed.

**Comment by pvretano** [comment]
04-OCT-2021: The extents object is a reused building block for common/features.  It is used in the collection object and we are reusing it here.  The intent is that the object is extensible so, besides spatial extent and temporal extent other extents (e.g. thermal, etc.) can be added.  While the consideration of flattening the structure so that the information is more clearly visible in GeoJSON clients is important, if we flatten extents then the same argument could be made to themes too which is not very amenable to being flattened.  One last point, if we flatten it here then we would be introducing yet another structure for extents besides what is defined in common/features and JSON-FG (where,when).  The feeling of the SWG right now is to leave it as it is.  We will move this into the "waiting for more feedback" column an see if more comments are provided.

**Comment by pvretano** [comment]
07-FEB-2022:  The extents objects that records uses are inherited from features and common and it is unlikely that we will change these at this point.  Closing for now but can be reopened if the issue still needs consideration.
