### ISSUE TITLE
Description of the two OpenSearch projects is unclear & verbose.

### ISSUE THREAD

**Issue by alcinnz** [opengeospatial/ogcapi-records#151]
The description of Amazon's new OpenSearch project could neatly be summarised as a "fork of the ElasticSearch 2.7 & Kibana 7.10.2 search suite". Rereads indicate the additional detail in the existing wording is trying to hint at a licensing kerfuffle motivating this fork, but this was not clear.

And the description of the OpenSearch protocol is a run-on sentance which wouldn't be understood by anyone who doesn't already know what it's trying to say. For the purpose of the report I'd write that "the OpenSearch protocol defines an XML description document describing how to request search results from a service. If these search results are encoded in ATOM or RSS this allows results from multiple services to be combined." Also: Firefox never supported OpenSearch *syndication*.

Furthermore I feel my sentiments in the discussion that there isn't a replacement in favor of which OpenSearch can be deprecated, which is why I believe the listed communities are still using it, is not captured. I would suggest the report state the now seperate conformance class "would allow the conformance class to be easily deprecated *or renamed* in the future".

P.S. After the codesprint, the OpenSearch Protocol updated [their README](https://github.com/dewitt/opensearch#how-is-it-related-to-the-opensearch-software-project) to clarify project status & disambiguate.

**Comment by pvretano** [comment]
07-DEC-2021: The OpenSearch-based OGC specifications all reference the [OASIS OpenSearch specification](https://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part4-opensearch/searchRetrieve-v1.0-os-part4-opensearch.html).  The [OASIS OpenSearch specification](https://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part4-opensearch/searchRetrieve-v1.0-os-part4-opensearch.html), in turn, states that is attempts to be fully compatible with http://www.opensearch.org/Specifications/OpenSearch/1.1/Draft_5 and this is where the chain breaks because this last URL points a completely different OpenSearch that has something to do with Elastic Search.  The "OpenSearch 1.1" is now being hosted and maintained at https://github.com/dewitt/opensearch.  I am not exactly sure what this means for OGC.  Perhaps nothing since the "OpenSearch 1.1" reference in the OASIS specification is NOT a normative reference.

**Comment by pvretano** [comment]
Updated to README to provide a very brief description of OpenSearch based on @alcinnz description.  The update also mentions the history of OpenSearch, its current status and the fact that it have been moved into its own part, Part 2.

**Comment by pvretano** [comment]
07-MAR-2022: Because there seems to be a large community (EO) that still uses OpenSearch the current plan it to clean up the extension document and move it ahead with the core.  Once the document is cleaned up to the point where it can be reviewed, I'll send a message out (probably to the TC I guess) to solicit review.  At that point we can gauge interest and see if we want to pour in more resources to move the document to adoption.

**Comment by pvretano** [comment]
Just checked in the text for the OpenSearch extension.  It is far, far, far from comeplete but much better than it was.  I am hoping interested parties will review and generate PRs to improve.

**Comment by pvretano** [comment]
7-APR-2023:  OpenSearch conformance class has been removed from the core and is now it's own extension (i.e. [Part2](https://github.com/opengeospatial/ogcapi-records/tree/master/extensions/OpenSearch)).
