### ISSUE TITLE
contact points as list

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#154]
Currently, [`recordGeoJSON.yaml`](https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordGeoJSON.yaml) records model has `contactPoint` and `publisher` objects which are in the spirit of DCAT.

Should we consider having a `contacts` list of 1..n `contactPoint` objects to be able to provide multiple contacts, with qualifying by role?

**Comment by pvretano** [comment]
@tomkralidis I am not opposed to that ... I believe that would align closer with what STAC does ... no?

**Comment by tomkralidis** [comment]
Good point @pvretano.  Yes, the [STAC collection spec](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#collection-fields) allows for a list of [`provider`](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#provider-object) objects.

Options:
1. add `contacts`, keep `contactPoint` / `publisher`
2. add `contacts`, remove `contactPoint` / `publisher`
3. other options?

The `contacts` list would be 1..n `responsibleParty` objects (to be reviewed via #155).

**Comment by pvretano** [comment]
29-NOV-2021: So we have two issues here.  Issue 1 is do we use a single key to convey contact/provider/publisher information like STAC does with its `providers` key OR do we use multiple keys like DCAT's `contactPoint` or `publisher`.  Issue 2 is: are these values single values or arrays?  The consensus of the SWG is that there should be a single key that is an array to convey the contact point/provider/publisher information.  It was felt that this approach was more scaleable since additional roles could be added without a proliferation of additional keys.  The name of the key should be something generic since names like `contacts`, `contactPoint`, `publisher` imply some kind of role already.  The key name `responsibleParties` was floated.  STAC follows the same approach but uses the key `providers` so, in order to align with STAC we might want to use `providers` with the starting roles of STAC.  @tomkralidis will create a PR to consider.

**Comment by tomkralidis** [comment]
Implemented in #156
