### ISSUE TITLE
add security to record model link object

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#170]
Data providers may wish to provide access control information in the context of a given link object (OAuth2, Basic Auth, API key, etc.).  Note that this is different than providing security information in the OpenAPI document (which is relevant to the API definition itself, rather than a metadata record's access links.

Should we consider adding support for security to links?  One option is to add a `security` object and reuse what OpenAPI provides (https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#security-scheme-object), which is referred to by OGC API - Common.

```json
{
    "rel": "download",
    "type": "application/json",
    "title": "link to WAF endpoint",
    "href": "https://example.org/data",
    "security": {
      "type": "http",
      "scheme": "basic"
    }
}
```

**Comment by pvretano** [comment]
11-JUL-2022: While this is useful information it seems a little premature to disucss in our SWG since the topic is more general than just "geo".  It would be good to engage with the IRTF (https://github.com/ietf-wg-httpapi) group and see what their thoughts are about including security information in a link ... or even ask if they considered it and if they did, why did they reject the notion.

**Comment by pvretano** [comment]
I think the work in "T18 Secure Asynchronous Catalogues" might be informative here.  I'll try to find some relevant links.

**Comment by pvretano** [comment]
28-NOV-2022:  The general feeling is that this is outside the scope of the OAPIR SWG.  However, the "T18 Secure Asynchronous Catalogues" ER may provide some additional insight.  That ER is now available for review by the SWG [here](https://portal.ogc.org/files/?artifact_id=102884&version=1).  I will leave this issue open till the next meeting and then we can close.
