### ISSUE TITLE
Finish chapter 6 Overview

### ISSUE THREAD

**Issue by lvdbrink** [opengeospatial/ogcapi-records#171]
Chapter 6 of OGC API Records Core seems to still need some work: 
- some headings start with "tl;dr", this needs to be addressed
- there is a Note at the start about the need to add a discussion about migration from big repositories of metadata to distributed crawlable catalogues
- I suggest reordering the chapter. Start with what is now 6.4 General and 6.5 Building Blocks, integrate 6.1-6.3 into what is now 6.5, then the rest.
- the second and third paragraph of 6.8.2. API Behaviour Model could perhaps be deleted. As a reader I don't find they are necessary / don't contain need to know information.
- Tables 5 and 6 in chapter 6 are repeated in chapter 7 and further, in the conformance classes. In chapter 6 I think just a summary and a reference to the full table in the conformance class would be enough, e.g. "he core set of properties that may be used to describe a record collection or catalogue include id, title and description. See table xx for the full set."

**Comment by pvretano** [comment]
08-AUG-2022 SWG Meeting: @pvretano will review and address.

**Comment by pvretano** [comment]
Made the following changes:
(1)  Moved all the tl;dr clauses to an informative annex called "implemenation Summaries".
(2) I reordered the clauses as suggested BUT moved 6.1-6.3 to an annex as described in (1).
(3) Removed the last paragraph from the "API Behavioural Model" clause.  Paragraph 2 is highlighting the fact that CSW is based on a single metadata repository while OARec operates on any number of metadata repositories (i.e. collections).  That seems like useful information to me.
(4) Removed the tables from clause 6 a simply reference the appropriate tables of properties from the other clauses.

**Comment by lvdbrink** [comment]
Thanks Peter, I'm happy with the changes!

Agreed about the Note; maybe we should start chapter 6 with a new paragraph titled "Role of OGC API Records" or something similar, where we explain what we envisage this role to be. I agree with the point that the Note makes.

I'll have a first go:

"Althought OGC API Records is built upon the legacy of CSW, its role in a modern SDI is a different one: catalogues will no longer be big repositories of metadata documents (e.g. ISO19115) like in traditional SDIs. Instead the architecture of a modern SDI is one of distributed, crawlable catalogies (e.g. static STAC). Resources are harvested into the catalogue to make them searchable. These resources can be metadata records close to resources, such as STAC items, or even collection objects."

... and then perhaps a few more sentences, I think we can probably get some content from the Abstract.

It would be great to also have a figure to illustrate this. Maybe someone has one from a presentation slide deck? 

Probably keep the Note in the document though, for discussion during the Code Sprint.

**Comment by pvretano** [comment]
I can contribute something I wrote in an email some time ago in relation to the Sept. code sprint.  I include it here in case we can canablize some of the content and combine it with @lvdbrink intro.

--- cut here ---
In today's Record SWG meeting we had a discussion about about a few of items that we felt should be discussed/tested at the code sprint.

Because ISO will be part of the code sprint, the Records SWG felt this would be a good opportunity to discuss the current role of metadata.  Specifically, the Records SWG discussion centered around the idea that historically, catalogues have been used as big repositories of formal metadata like 19119, 19115, FGDC. etc. However, more recently catalogues are migrating to a more distributed model where the metadata is intimately associated with the resource that it describes.  In this scenario, the catalogue records can be distributed and linked together so that they can be crawled OR they can be harvested into a service endpoint to make them searchable.  Even more than that, a searchable catalogue can harvest not only a metadata document describing the resource but in some cases the resource itself (e.g. harvesting the collections object from OGC API).  STAC, of course, is the example that comes to mind of this new approach to cataloging which relies on well defined building blocks that can be hooked up in different ways. The implications of this, I think, are subtle but important.  In the traditional cataloging approach (say based on CSW) you could find the record and the record might include binding information to access the resource but that is pretty much it.  Using the new approach, a client interacts more intimately with the catalogue and the catalogue becomes integral to the access to the resource. Think of the entire cloud native ecosystem.  Range requests to COGs don't really work unless you have a STAC item telling you in what ranges the bands exists.  And so the catalogue becomes an integral component in the process of accessing a resource. Anyway, we though this would be a good topic of discussion at the Sept. code sprint."
--- cut here ---

**Comment by pvretano** [comment]
28-NOV-2022: @pvretano will handle the comments refered to in the previous comment in this issue and then close.

**Comment by pvretano** [comment]
07-APR-2023: @kalxas will review and close.
