### ISSUE TITLE
Clarify bbox and datetime parameters

### ISSUE THREAD

**Issue by lvdbrink** [opengeospatial/ogcapi-records#175]
Apologies in advance if this question has already been addressed; I have not been present for most of the earlier SWG meetings. 

Requirement 27 C states: 
> The bbox parameter SHALL match all records in the collection that are not associated with a spatial geometry, too.

Requirement 29 C states the same for `datetime`. 

So if you query for records within a certain bbox, you also get all records that don't have a spatial geometry specified. Isn't it contra intuitive that a query using `bbox` should return records that don't have a geometry, or the same for `datetime`? What is the reason behind these requirements?

**Comment by cportele** [comment]
@lvdbrink - This behaviour is inherited from Features and dates back to a discussion/decision during the early stages of that spec. Here is the issue: https://github.com/opengeospatial/ogcapi-features/issues/121. 

I think there are arguments for both approaches, to ignore items that do not have an explicit spatial/temporal geometry or to include them in the result set. This will depend on what the specific meaning of "no location" in a resource is. If it is "the thing has a location, but it is unknown", then the current behaviour seems adequate, because the thing might be located in the bbox. If the meaning is "the thing is not spatial" and the intent of the bbox filter in the query is to only retrieve spatial things then the result is probably a surprise.

It is a long time ago since we made the decision, but I think the reasoning was that "unknown" was the typical case, if things in a collection had a geometry property and no geometry was set for some of them.

If the API supports CQL2 filters, you can send specific requests by using the spatial operators and, if desired, the `IS NULL` operator. For example, if you just use `S_INTERSECTS(geometry,ENVELOPE(...))` then you won't get the items where `geometry` is `NULL`. If you use `S_INTERSECTS(geometry,ENVELOPE(...)) OR geometry IS NULL`, you will get those, too.

**Comment by lvdbrink** [comment]
Thank you for the clarification!

**Comment by pvretano** [comment]
08-AUG-2022 SWG Meeting:  The explanation is sufficient and clear.  Closing issue.
