### ISSUE TITLE
The GUF.SWG wants to define an extension of OGC API records for feedback

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-records#229]
Rationale:
* So far, Geospatial User Feedback (GUF) is only a data model (and an XML implementation) and the group never defined an API.
* It is time to define an API for feedback!
* We assume that User feedback is another form of metadata that is also stored in "records".

Proposal:
While it can be good to base the new standard in OGC API records, we would like to have a way to differentiate among the different record types. So: A collection description that contains Geospatial User Feedback such as: ...\collections\UserFeedback will return a JSON description with a property 
"itemType": "record"
and it will need to have another property to differentiate between "producer" metadata (the common one) and the "user" metadata. We propose to use:
"recordType": "feedback"

This way, the a client will be able to know that this collection conforms to the "OGC API feedback" (if that is the final name) and apply the new requirements and GUF data model to this collection only. 

An alternative could be to have "itemType": "feedback" but this will mean that feedback is not a record and that does not seem to be case.

We would like to get the support of this group (OGC API records SWG) to this decision (or a good reason for doing this differently)

Thanks,

(more info on the GUF.SWG intentions here: https://github.com/opengeospatial/Geospatial-User-Feedback)

**Comment by pvretano** [comment]
@joanma747 this is a duplicate issue.  See https://github.com/opengeospatial/ogcapi-records/issues/26 and https://github.com/opengeospatial/ogcapi-records/issues/215.  Basically you can use the `conformsTo` member, either at the collection level or the record level to indicate a record type or (in other words) a record that has been augmented or extended with additional members that conform to some well know specification (e.g. DCAT, ISO19115 or GUF too I suppose since it sounds like you have a data model already described).

**Comment by pvretano** [comment]
01-MAY-2023:  @joanma747 ok to close this as duplicate of #23 and #215?

**Comment by joanma747** [comment]
I verified it and it sounds like a good solution (conformsTo collection). Our OGC API GUF will specify a set of conformance classes that will be referenced in the conformsTo member.

We can close the issue.
