### ISSUE TITLE
cql-filter requirements class without conformance class

### ISSUE THREAD

**Issue by ycespb** [opengeospatial/ogcapi-records#284]
The specification uses a requirements class URI for cql-filter ( http://www.opengis.net/spec/ogcapi-records-1/1.0/req/cql-filter) while other capabilities are identified by their conformance class (e.g. in https://docs.ogc.org/DRAFTS/20-004.html#_core).  Should there not be a corresponding "conformance class" URI and should the conformance class URI /conf/ be listed in the /conformance response or should the /req/ URI be included in the /conformance response or none of the two ?   The same /req/ URI is borrowed by STAC where it is used as "conformance class". See also https://github.com/stac-api-extensions/collection-search/issues/9 .

**Comment by m-mohr** [comment]
Related to #283, I guess.

**Comment by pvretano** [comment]
Actually, all the conformance URIs referenced in the permission should be references to requirements.  I should also update the URI to be `/req/searchable-catalogue/requirements` rather than `/req/searchable-catalogue/conformance`.  These requirement URIs are not meant to be listed in the `/conformance` declaration; those are actually listed [here](https://docs.ogc.org/DRAFTS/20-004.html#_conformance_testing).
