### ISSUE TITLE
OGC link relations

### ISSUE THREAD

**Issue by cdharbin** [opengeospatial/ogcapi-records#316]
Currently we implement a server that supports OGC API Records. We also have a client implementation. Our workflow is for our OGC API Records client to browse collections or search the catalog for results. When we display search results from the catalog in our client, it's not html because it's an internal format.  we want to provide links to show a thumbnail, a link to an OGC WMS request to add a layer to the map and the ability to download the resource and it's associated resources.  In order for our client to read other 3rd party OGC API Records implementations, it would be good to know if there would be any standardized relations for OGC WMS, thumbnails and download types?

We have an OGC WMS to add to map that needs to support a request with a layer name. It can be older versus newer OGC WMS standard. We currently put the layer name in the title field and define the relation as a service. Have you seen OGC WMS relation  provided by 3rd party implementations? If so, is this standardized in any OGC API standard?
"href": "http...",   
"type" : "ogc:wms",
 "title" :  "layername",
"rel" : "service"

We have a link to display a thumbnail in the search results. Is preview the correct relation name? I noticed that one of the github OGC API implementations used thumbnail in the title but wasn't sure if I needed to look at both places.
"href": "http...",   
"type" : "image/png",
 "title" :  "thumbnail",
 "rel": "preview"

We provide the option to download the resource returned in the search result. Would enclosure the appropriate relation type? If so, is this type of relation standardized in any OGC API standard?
"href": "http...",   
"type" : "application/octet-stream",
 "title" :  "download",
 "rel": "enclosure"

**Comment by kalxas** [comment]
Please have a look here for a previous effort:
https://github.com/OSGeo/Cat-Interop/blob/master/LinkPropertyLookupTable.csv

**Comment by pvretano** [comment]
13-NOV-2023: The concensus of the SWG is that `rel="preview"` and `rel="enclosure"` are the correct relations for thumbnails and download packages but we are not sure that we need to say anything about that in the Core specification since these are standard IANA link relation already.  In Features, for example, there are examples of the use of `enclosure` but there are no requirements or recommendation about that in the specification.  We should probably stick with that in Records too.  @pvretano will add some examples, based on this issues, to the specification about the use of `preview` and `enclosure`.
