### ISSUE TITLE
clarify items datetime parameter

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#38]
In the spirit of http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_parameter_datetime, how do we address the `datetime` parameter in OARec?

- in the same way/consistent with OAFeat
- associating OARec's `datetime` to a record's [`extents.temporal` object](https://github.com/opengeospatial/ogcapi-records/blob/master/core/examples/json/example_record.json#L25-L32)
- something else?

In addition, we should make clear that datetime should be `YYYY-MM-DDThh:mm:ss[Z]` (and whether or not any partials are supported (like `YYYY`, `YYYY-MM`, `YYYY-MM-DD`).

**Comment by pvretano** [comment]
21-SEP-2020: The basic issue is whether we allow datetime to be specified using a convenience ... e.g. datetime=2020-09-21 versus datetime/2020-09-21T00:00:00/2020-09-21T11:59:59.
@pvretano does not want to stray too far from what common and features define in this respect
@tomkralidis might be important for catalogue
@cportele perhaps we need to gather further feedback from client implementers before making a decision
@pvretano will add a not in the core specification asking for feedback

**Comment by pvretano** [comment]
28-DEC-2020: The specific aspects of this issue that need to be clarified are:

- granularity -> does clients need to specify the entire RFC string or can shortcuts be used (e.g. datetime=2020-09-21) rather than having to specify the entire datatime string (e.g. 2020-09-21T00:00:00); this could also be extended to be able to say something like datetime=2020 to mean the entire year of 2020
- when someone actually says datetime=<> what does that mean in terms of what property(ies) is/are used to resolve the predicate?

The answer to the second issues is related to "levels" of query capability ...

- at the first level of query capability it is up to the server to select which spatial and temporal properties are used to resolve bbox and datetime predicates (this is the situation in feature core and records core right now)
- the next level up of query capability add more flexibility in terms of the kinds on geometries that may be used for spatial and temporal queries and the types of operators that may be applied but still leaves if up to the server to select the property(ies) that will be used to evaluate the predicates.
- at the top level, something like CQL, the client has full control over which properties (queryables) are used to resolve the predicated, which operators are used, etc.

**Comment by pvretano** [comment]
SWG MEETING: 08-FEB-2021: With regard to granularity, right now it makes sense to be consistent with features (i.e. the complete datetime string needs to be specified).  It is a question whether shorting should be supported but if it is, it should be something in another extension or conformance class.  Which property the datatime is applied to remains as described above (i.e. server choice)

**Comment by pvretano** [comment]
@tomkralidis is there any additional actions we need to take for this issue or can be close?

**Comment by tomkralidis** [comment]
@pvretano we can close.  Once we go out for public comment it will be valuable to get feedback on RFC3339 requirement (full datetime) from others.
