### ISSUE TITLE
Editorial issues in Records - Part 1: Core text for TC vote

### ISSUE THREAD

**Issue by PeterParslow** [opengeospatial/ogcapi-records#385]
https://docs.ogc.org/DRAFTS/20-004.html

Table 5: the path template for collections shows up oddly (some misaligned bracket resulting in link & text being separate)

8.2.12 more technical: why insist on the Apache SPDX license code for licences where the license publisher already provides a stable identifier (e.g. CC)? Is it "just" because URIs don't make good strings to exchange in a filter query? (That may be sufficient reason to answer my concern!)

**Comment by pvretano** [comment]
@PeterParslow I think it is the octothorp that needs to be escaped in asciidoc.  I'll fix that.  

The primary reason for using SPDX is because we, OGC I mean, negotiated with STAC so that both standards use the same mechanism for including license information in a record.  Since STAC had primacy and no one in the SWG objected, we simply used what STAC had.  However, strings (rather that URIs) would make easier to search in a filter query too ...
