### ISSUE TITLE
Convert OpenAPI schema "example" to "examples" array

### ISSUE THREAD

**Issue by kalxas** [opengeospatial/ogcapi-records#396]
It has been reported that some tools that convert OpenAPI schemas to JSONSchema have an issue converting example to examples.

https://github.com/ESA-EarthCODE/open-science-catalog-metadata/issues/233#issuecomment-2401039378
https://github.com/ESA-EarthCODE/open-science-catalog-metadata/issues/233#issuecomment-2411009208
https://github.com/ESA-EarthCODE/open-science-catalog-metadata/issues/233#issuecomment-2452959385
https://github.com/ESA-EarthCODE/open-science-catalog-metadata/issues/233#issuecomment-2452995074

Should we consider switching the YAML schema `example` to `examples` to avoid doing it manually during conversion?

**Comment by pvretano** [comment]
@kalxas I'll update all instances of "example" to be "examples'.  I just checked the JSON Schema specification and it seems that the correct key name is "examples".

**Comment by kalxas** [comment]
@pvretano thank you

**Comment by pvretano** [comment]
OK ... the change from "example" to "examples" causes validation of the example openAPI files to fail so I have to undo these changes.  For example, when I changes all instances of "example" in `linkBase.yaml` to "examples" (and converted the example to an array) swagger-cli spewed forth a long list of "additional parameters not allowed" errors.  I think this is because the version of JSON schema that swagger-cli understands is not pure JSON schema.

**Comment by kalxas** [comment]
ok, let's revert then

**Comment by m-mohr** [comment]
That's weird, especially given that OpenAPI 3.1 deprecates example:

> Deprecated: The example property has been deprecated in favor of the JSON Schema examples keyword. Use of example is discouraged, and later versions of this specification may remove it.
