### ISSUE TITLE
update specification title

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#4]
It appears that the names of the specifications are being updated to more reflect a resource oriented architecture:

old name|new name
----------|----------|
OGC WCS|OGC API - Coverages
OGC WPS|OGC API - Processes
OGC WMTS|OGC API - Map Tiles
OGC OWS Common|OGC API - Common

Should we consider the same for CAT 4.0?  Suggestions:

a. OGC API - Metadata
b. OGC API - Catalogue
c. something else?

My vote would be for b given 'Metadata' is probably an overloaded term.  Thoughts?  I can update the repo accordingly once we have consensus.

**Comment by cportele** [comment]
Since the main resources are records, I suggest "OGC API - Records".

Or maybe "OGC API - Catalogues and Records".

**Comment by uvoges** [comment]
The objective of this API (that what is indexed, used for searching, primary response,...) is for sure metadata (regardless whether the resources being described are EO products, services, processes, catalogues, code lists...). So "OGC API - Metadata" or similar would fit.

**Comment by cportele** [comment]
> The objective of this API is for sure metadata ...

I disagree. Yes, metadata records are one type of records that are in scope, but not the only one.

**Comment by uvoges** [comment]
Could you describe the response of a catalogue search (or what is being indexed) handling records you have in mind ?

**Comment by cportele** [comment]
An example: Managing and sharing code lists and their values. Each value is a record in a catalogue / register. Note that this is not about indexing.

**Comment by tomkralidis** [comment]
IMHO Metadata is an overloaded term IMHO. In addition if we look at previous specifications and schema we see that csw:Record was the basic information unit. +1 for OGC API - Records.

**Comment by uvoges** [comment]
I guess catalogue is per definition about indexing and search (otherwise we have data access). 
Independant what is indexed this is done by information which represents the resource that is being indexed (this is usually called metadata). Anyway we have different resources that have some basic information (or metadata) and operations (e.g. search capabilities) in common. Maybe we could call this basic information "Record". I guess from this basic information (and operations) we can derive different more or less complex metadata models, e.g. as complex as that of an EO product (see OGC 17-003) or a s simple as that of a codeList for colours (red, blue, green,..). In the latter case the difference between the metadata and data begins to disappear athough there is also some kind of metadata which is being indexed (e.g. to be able to search for a codelist of colours).

I guess every resource being derived from Record brings its own more or less complex search facilities (search model, search operations, search response) which should be defined in a kind of profile...
A Registry may be a very specific case of a Catalogue where no (?) search (and so no indexing) is needed.

**Comment by bradh** [comment]
Catalog / Catalogue makes perfect sense if you're coming from CSW 3. Otherwise, something like "index", "search" or "find" might be be more applicable. I recognise that a verb is a bit different to the other "OGC API - noun" concepts.

**Comment by pvretano** [comment]
@bradh I like "OGC API - Search/Find" but that could apply to any resource type.  Perhaps OGC API - Discovery?   At some point we are going to have to list all these names and vote! ;)

**Comment by uvoges** [comment]
..isn´t Search/Find also valid for Features ?
What is the subject of the Search/Find ?

**Comment by cportele** [comment]
Meeting 2019-12-02: Use "OGC API - Records" (for now).

**Comment by cportele** [comment]
SWG Meeting 16-DEC-2019: We keep it open until the text in the repo has been updated to reflect it.

**Comment by cportele** [comment]
The text has been updated and we can close this issue.
