### ISSUE TITLE
Clarify Filter and CQL usage

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-records#47]
Work is on-going in OGC API - Features SWG developing an extension for Filtering and CQL.

The Filtering and CQL extension will, at a later stage, be [moved](https://github.com/opengeospatial/ogcapi-features/issues/423#issuecomment-668057132) into OGC API - Common.

There's a need to discuss how a future extension of OGC API - Records could support a similar Filtering and CQL capability.

Please coordinate with the OGC API - Features SWG on this topic.

**Comment by ghobona** [comment]
2020-09-15 OGC Member Meeting.

SWG decision: The OGC API - Records SWG agrees that the [conformance class should be moved to OGC API - Common](https://github.com/opengeospatial/ogcapi-features/issues/423#issuecomment-668057132) at a later stage, when ready.

**Comment by pvretano** [comment]
11-JAN-2020: Should we have a conformance class for CQL?  Clemens thinks we should add a conformance class since we already have a discussion about the various query levels AND we include OpenSearch.  Since the section would be small, basically copy the features CQL binding and adopt for records, Peter will add it.
