### ISSUE TITLE
Security considerations ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#49]
The purpose of this issue is to solicit any security considerations that should be specified in the core.   I assume that baseline security considerations would be the same as features (see https://github.com/opengeospatial/ogcapi-features/blob/master/core/standard/clause_11_security_considerations.adoc).  If there are any others, we should capture them in this issue.

**Comment by ghobona** [comment]
2020-09-15 OGC Member Meeting.

Provide the means to protect any type of query. This may need to be done in OGC API- Common. Comment from @chris-little

We should not restrict to any particular security approach. Comment from Michael Gordon.

Protection of metadata elements ?

OGC API - Records should not have something specific to it, for protecting metadata elements. Because it could use approaches applicable to Features API as well. Comment from Frederic Houbie.

Not publishing metadata may be the best option. Comment from Chris.

Isn't the metadata simply providing information about a thing. The metadata may not necessarily be sensitive. Alex.

Need to consider whether the security restrictions on accessing the data are represented in the metadata. Michael.

The work on Data Centric Security in Testbed-15 & 16 is may be relevant.

**Comment by pvretano** [comment]
2020-09-21: 
Clemens: Don't need to get too deep into this issue; we only need to worry about vulnerabilities and may use common for features as a reference for that content.

**Comment by pvretano** [comment]
07-FEB-2022: Just a reminder for @pvretano to engage with Andreas about what types of considerations we need to think about.

**Comment by pvretano** [comment]
31-MAR-2023:  Since the API for record is essentially the features API we should just reference the security considerations section from features (see: https://docs.opengeospatial.org/is/17-069r4/17-069r4.html#_security_considerations).

**Comment by tomkralidis** [comment]
PR in #224

**Comment by ghobona** [comment]
@securedimensions This discussion might be of interest to you.

**Comment by pvretano** [comment]
07-APR-2023:  @tomkralidis added security considerations content to the specification (#224) which was merged at the last SWG meeting.
