### ISSUE TITLE
Time parameter ambiguity

### ISSUE THREAD

**Issue by mhogeweg** [opengeospatial/ogcapi-records#55]
working on implementing the draft spec, I run into the specification of the time parameter as used in `/collections` and `/collections/:collectonId/items`.

I would recommend deciding specifically what temporal property should be considered for the time parameters. In geospatial metadata there are many dates describing when a resource was created/updated/published, when the metadata for the resource was created/updated/published, when things got added/updated to catalogs, etc.

it makes a big difference to query for data for October 2020 that is the latest landsat collected in October 2020 vs querying for landsat content from October 1980 that just happened to have been added to a catalog in October 2020.

**Comment by pvretano** [comment]
19-OCT-2020: At this level, this ambiguity is intentional.  We can't, for example, know at this level what date properties a particular community of interest might have and different communities will have different properties.  So, we leave it up to the server to decide; communities of interest can, of course, impose rules about which properties the operators are applied to.  An additional point, as the you move up the query complexity "ladder" from this level at core all the way up to something like CQL the ability of the client to control which properties operators are applied to increases.
